apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa-api-strapi
  namespace: hpa-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nuageit-delivery-bhairport-api-strapi
  template:
    metadata:
      labels:
        app: nuageit-delivery-bhairport-api-strapi
    spec:
      containers:
      - name: nuageit-delivery-bhairport-api-strapi
        image: <sua-imagem-aqui> # Substitua pela imagem do seu container
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"