apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008 #se você não colocar nada aqui ele vai escolher automaticamente.
  selector:
    app: myapp
    type: front-end #são da pasta do pod-definition. apenas pegamos seus labels